#!/usr/bin/env python

import os
import sys
import argparse

if __name__=="__main__":
	rootdir = os.path.dirname(os.path.realpath(sys.argv[0]))

	parser = argparse.ArgumentParser('./twitchy')

	parser.add_argument('channel_name', help="Name of the twitch channel")
	parser.add_argument('-na', '--no-audio', action="store_true", help="Disable audio (default: enable audio)")
	parser.add_argument('-nv', '--no-video', action="store_true", help="Disable video (default: enable video)")
	parser.add_argument('-v' , '--verbose' , action="store_true", help="Show more output (default: disabled)")
	parser.add_argument('-s' , '--screen'  , action="store_true", help="Start the stream in a screen session (default: disabled)")

	args = parser.parse_args()

	if args.verbose:
		print ("Current directory: " + os.getcwd())
		print ("Twitchy location:  " + rootdir)

	print ("Opening the " + args.channel_name + " stream")
	
	os.system(
		("screen -mS twitch " if args.screen else "") +
		"cvlc " +
		"--play-and-exit " + 
		("-q " if not args.verbose else " ") + 
		("--no-video " if args.no_video else " ") + 
		("--no-audio " if args.no_audio else " ") + 
		"$(python '" + 
		rootdir + 
		"/tlu/twitch_live_url.py' " + 
		args.channel_name + 
		" | grep 'chunked')"
	)
